/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDexCallee__factory } from "./IDexCallee__factory";
export { IDexFactory__factory } from "./IDexFactory__factory";
export { IDexKIP7__factory } from "./IDexKIP7__factory";
export { IDexPair__factory } from "./IDexPair__factory";
export { IDexRouter__factory } from "./IDexRouter__factory";
export { IPlatformToken__factory } from "./IPlatformToken__factory";
export { IWKLAY__factory } from "./IWKLAY__factory";
