FROM node:lts as build

ARG VITE_APP_GRAPHQL_URI_EXCHANGE
ENV VITE_APP_GRAPHQL_URI_EXCHANGE=$VITE_APP_GRAPHQL_URI_EXCHANGE

ARG VITE_APP_GRAPHQL_URI_FARMING
ENV VITE_APP_GRAPHQL_URI_FARMING=$VITE_APP_GRAPHQL_URI_FARMING

ARG VITE_APP_GRAPHQL_URI_STAKING
ENV VITE_APP_GRAPHQL_URI_STAKING=$VITE_APP_GRAPHQL_URI_STAKING

ARG VITE_APP_GRAPHQL_URI_SNAPSHOT
ENV VITE_APP_GRAPHQL_URI_SNAPSHOT=$VITE_APP_GRAPHQL_URI_SNAPSHOT

ARG VITE_APP_SNAPSHOT_SPACE
ENV VITE_APP_SNAPSHOT_SPACE=$VITE_APP_SNAPSHOT_SPACE

ARG VITE_APP_DASHBOARDS_HREF
ENV VITE_APP_DASHBOARDS_HREF=$VITE_APP_DASHBOARDS_HREF

WORKDIR /app

COPY . .

RUN npm install -g pnpm
RUN pnpm install
RUN VITE_APP_GRAPHQL_URI_EXCHANGE=$VITE_APP_GRAPHQL_URI_EXCHANGE \
    VITE_APP_GRAPHQL_URI_FARMING=$VITE_APP_GRAPHQL_URI_FARMING \
    VITE_APP_GRAPHQL_URI_STAKING=$VITE_APP_GRAPHQL_URI_STAKING \
    VITE_APP_GRAPHQL_URI_SNAPSHOT=$VITE_APP_GRAPHQL_URI_SNAPSHOT \
    VITE_APP_SNAPSHOT_SPACE=$VITE_APP_SNAPSHOT_SPACE \
    VITE_APP_DASHBOARDS_HREF=$VITE_APP_DASHBOARDS_HREF pnpm build

FROM nginxinc/nginx-unprivileged:1.20
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
