FROM node:lts as build

ARG VITE_GRAPHQL_URI_EXCHANGE
ENV VITE_GRAPHQL_URI_EXCHANGE=$VITE_GRAPHQL_URI_EXCHANGE

ARG VITE_GRAPHQL_URI_FARMING
ENV VITE_GRAPHQL_URI_FARMING=$VITE_GRAPHQL_URI_FARMING

ARG VITE_GRAPHQL_URI_STAKING
ENV VITE_GRAPHQL_URI_STAKING=$VITE_GRAPHQL_URI_STAKING

ARG VITE_GRAPHQL_URI_SNAPSHOT
ENV VITE_GRAPHQL_URI_SNAPSHOT=$VITE_GRAPHQL_URI_SNAPSHOT

ARG VITE_SNAPSHOT_SPACE
ENV VITE_SNAPSHOT_SPACE=$VITE_SNAPSHOT_SPACE

ARG VITE_DASHBOARDS_HREF
ENV VITE_DASHBOARDS_HREF=$VITE_DASHBOARDS_HREF

ARG VITE_ROUTER_HASH_MODE
ENV VITE_ROUTER_HASH_MODE=$VITE_ROUTER_HASH_MODE

WORKDIR /app

COPY package.json package.json

RUN npm install -g pnpm && \
            pnpm install

COPY . .

RUN VITE_GRAPHQL_URI_EXCHANGE=$VITE_GRAPHQL_URI_EXCHANGE \
    VITE_GRAPHQL_URI_FARMING=$VITE_GRAPHQL_URI_FARMING \
    VITE_GRAPHQL_URI_STAKING=$VITE_GRAPHQL_URI_STAKING \
    VITE_GRAPHQL_URI_SNAPSHOT=$VITE_GRAPHQL_URI_SNAPSHOT \
    VITE_SNAPSHOT_SPACE=$VITE_SNAPSHOT_SPACE \
    VITE_DASHBOARDS_HREF=$VITE_DASHBOARDS_HREF \
    VITE_ROUTER_HASH_MODE=$VITE_ROUTER_HASH_MODE pnpm build

FROM nginxinc/nginx-unprivileged:1.20
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
