/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as multiCallSol from "./MultiCall.sol";
export * as access from "./access";
export { KIP13__factory } from "./KIP13__factory";
