/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as wklaySol from "./WKLAY.sol";
export { PlatformToken__factory } from "./PlatformToken__factory";
export { TestToken__factory } from "./TestToken__factory";
