/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDexCallee } from "./IDexCallee";
export type { IDexFactory } from "./IDexFactory";
export type { IDexKIP7 } from "./IDexKIP7";
export type { IDexPair } from "./IDexPair";
export type { IDexRouter } from "./IDexRouter";
export type { IPlatformToken } from "./IPlatformToken";
export type { IWKLAY } from "./IWKLAY";
