/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as deflatingKip7Sol from "./DeflatingKIP7.sol";
export type { deflatingKip7Sol };
import type * as kip7TestMockSol from "./KIP7TestMock.sol";
export type { kip7TestMockSol };
export type { DexKIP7Test } from "./DexKIP7Test";
export type { KIP7Holder } from "./KIP7Holder";
export type { MathMock } from "./MathMock";
