/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKIP7TokenReceiver,
  IKIP7TokenReceiverInterface,
} from "../../../interfaces/IKIPReciever.sol/IKIP7TokenReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "onKIP7Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKIP7TokenReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IKIP7TokenReceiverInterface {
    return new utils.Interface(_abi) as IKIP7TokenReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKIP7TokenReceiver {
    return new Contract(address, _abi, signerOrProvider) as IKIP7TokenReceiver;
  }
}
