/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kip from "./KIP";
export type { kip };
import type * as access from "./access";
export type { access };
import type * as governance from "./governance";
export type { governance };
import type * as utils from "./utils";
export type { utils };
