/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIkip7PermitSol from "./draft-IKIP7Permit.sol";
export type { draftIkip7PermitSol };
import type * as draftKip7PermitSol from "./draft-KIP7Permit.sol";
export type { draftKip7PermitSol };
export type { IKIP7Metadata } from "./IKIP7Metadata";
export type { KIP7Votes } from "./KIP7Votes";
