/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ikipRecieverSol from "./IKIPReciever.sol";
export * as draftIkip7PermitSol from "./draft-IKIP7Permit.sol";
export { IAccessControl__factory } from "./IAccessControl__factory";
export { IDexCallee__factory } from "./IDexCallee__factory";
export { IDexFactory__factory } from "./IDexFactory__factory";
export { IDexKIP7__factory } from "./IDexKIP7__factory";
export { IDexPair__factory } from "./IDexPair__factory";
export { IDexRouter__factory } from "./IDexRouter__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IKIP13__factory } from "./IKIP13__factory";
export { IKIP7__factory } from "./IKIP7__factory";
export { IKIP7Metadata__factory } from "./IKIP7Metadata__factory";
export { IKIP7Receiver__factory } from "./IKIP7Receiver__factory";
export { IPlatformToken__factory } from "./IPlatformToken__factory";
export { IVotes__factory } from "./IVotes__factory";
export { IWKLAY__factory } from "./IWKLAY__factory";
