/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wklaySol from "./WKLAY.sol";
export type { wklaySol };
export type { PlatformToken } from "./PlatformToken";
export type { TestToken } from "./TestToken";
