/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wklaySol from "./WKLAY.sol";
export type { wklaySol };
import type * as extensions from "./extensions";
export type { extensions };
export type { KIP7 } from "./KIP7";
export type { PlatformToken } from "./PlatformToken";
export type { TestToken } from "./TestToken";
