/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  KIP13,
  KIP13Interface,
} from "../../../../../../@klaytn/contracts/KIP/utils/introspection/KIP13";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class KIP13__factory {
  static readonly abi = _abi;
  static createInterface(): KIP13Interface {
    return new utils.Interface(_abi) as KIP13Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): KIP13 {
    return new Contract(address, _abi, signerOrProvider) as KIP13;
  }
}
