/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCallSol from "./MultiCall.sol";
export type { multiCallSol };
import type * as access from "./access";
export type { access };
export type { KIP13 } from "./KIP13";
