/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCallSol from "./MultiCall.sol";
export type { multiCallSol };
import type * as stakingSol from "./Staking.sol";
export type { stakingSol };
import type * as stakingFactoryPoolSol from "./StakingFactoryPool.sol";
export type { stakingFactoryPoolSol };
export type { Farming } from "./Farming";
export type { StakingFactory } from "./StakingFactory";
