/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as draftKip7PermitSol from "./draft-KIP7Permit.sol";
export { KIP7Votes__factory } from "./KIP7Votes__factory";
