/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ExampleComputeLiquidityValue extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ExampleComputeLiquidityValue;
  clone(): ExampleComputeLiquidityValue;
  methods: {
    factory(): NonPayableTransactionObject<string>;

    getGasCostOfGetLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: number | string | BN,
      truePriceTokenB: number | string | BN,
      liquidityAmount: number | string | BN
    ): NonPayableTransactionObject<string>;

    getLiquidityValue(
      tokenA: string,
      tokenB: string,
      liquidityAmount: number | string | BN
    ): NonPayableTransactionObject<{
      tokenAAmount: string;
      tokenBAmount: string;
      0: string;
      1: string;
    }>;

    getLiquidityValueAfterArbitrageToPrice(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: number | string | BN,
      truePriceTokenB: number | string | BN,
      liquidityAmount: number | string | BN
    ): NonPayableTransactionObject<{
      tokenAAmount: string;
      tokenBAmount: string;
      0: string;
      1: string;
    }>;

    getReservesAfterArbitrage(
      tokenA: string,
      tokenB: string,
      truePriceTokenA: number | string | BN,
      truePriceTokenB: number | string | BN
    ): NonPayableTransactionObject<{
      reserveA: string;
      reserveB: string;
      0: string;
      1: string;
    }>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
