// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EarnWrap: typeof import('./components/EarnWrap.vue')['default']
    FarmingModule: typeof import('./modules/FarmingModule/index.vue')['default']
    FarmingModuleModal: typeof import('./modules/FarmingModule/Modal.vue')['default']
    FarmingModulePool: typeof import('./modules/FarmingModule/Pool.vue')['default']
    FarmingModuleStakeModal: typeof import('./modules/FarmingModule/Modal.vue')['default']
    FarmingModuleUnstakeModal: typeof import('./modules/FarmingModule/UnstakeModal.vue')['default']
    HeaderMenu: typeof import('./components/HeaderMenu.vue')['default']
    KlayAccordionItem: typeof import('./common/KlayAccordionItem.vue')['default']
    KlayButton: typeof import('./common/KlayButton.vue')['default']
    KlayCollapse: typeof import('./common/KlayCollapse.vue')['default']
    KlayIcon: typeof import('./common/KlayIcon.vue')['default']
    KlayLoader: typeof import('./common/KlayLoader.vue')['default']
    KlayModal: typeof import('./common/KlayModal.vue')['default']
    KlaySlider: typeof import('./common/KlaySlider/index.vue')['default']
    KlaySlippage: typeof import('./common/KlaySlippage.vue')['default']
    KlayTextField: typeof import('./common/KlayTextField.vue')['default']
    KlayWrap: typeof import('./common/KlayWrap.vue')['default']
    LiquidityModuleAdd: typeof import('./modules/LiquidityModule/Add/index.vue')['default']
    LiquidityModuleAddExchangeRate: typeof import('./modules/LiquidityModule/Add/ExchangeRate.vue')['default']
    LiquidityModuleAddModal: typeof import('./modules/LiquidityModule/Add/Modal.vue')['default']
    LiquidityModuleRemove: typeof import('./modules/LiquidityModule/Remove/index.vue')['default']
    LiquidityModuleRemoveAmount: typeof import('./modules/LiquidityModule/Remove/Amount/index.vue')['default']
    LiquidityModuleRemoveDetailed: typeof import('./modules/LiquidityModule/Remove/Detailed/index.vue')['default']
    NotificationsInit: typeof import('./components/NotificationsInit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slippage: typeof import('./components/Slippage.vue')['default']
    SwapModule: typeof import('./modules/SwapModule/index.vue')['default']
    SwapModuleDetails: typeof import('./modules/SwapModule/Details/index.vue')['default']
    SwapModuleExchangeRate: typeof import('./modules/SwapModule/ExchangeRate.vue')['default']
    TagName: typeof import('./components/TagName.vue')['default']
    TokenInput: typeof import('./components/TokenInput/index.vue')['default']
    TokenSelect: typeof import('./components/TokenSelect/index.vue')['default']
    TokenSelectModal: typeof import('./components/TokenSelect/Modal.vue')['default']
    TradeWrap: typeof import('./components/TradeWrap.vue')['default']
    Tutorial: typeof import('./components/Tutorial.vue')['default']
  }
}

export {}
