// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderMenu: typeof import('./components/HeaderMenu.vue')['default']
    KlayButton: typeof import('./common/KlayButton.vue')['default']
    KlayCharAvatar: typeof import('./common/KlayCharAvatar.vue')['default']
    KlayCollapse: typeof import('./common/KlayCollapse.vue')['default']
    KlayIcon: typeof import('./common/KlayIcon.vue')['default']
    KlayLoader: typeof import('./common/KlayLoader.vue')['default']
    KlayModalCard: typeof import('./common/KlayModalCard.vue')['default']
    KlaySlider: typeof import('./common/KlaySlider/index.vue')['default']
    KlaySlippage: typeof import('./common/KlaySlippage.vue')['default']
    KlayTextField: typeof import('./common/KlayTextField.vue')['default']
    KlayWrap: typeof import('./common/KlayWrap.vue')['default']
    ModuleLiquidityAdd: typeof import('./modules/ModuleLiquidity/Add/index.vue')['default']
    ModuleLiquidityAddDetails: typeof import('./modules/ModuleLiquidity/Add/Details.vue')['default']
    ModuleLiquidityAddDetailsRow: typeof import('./modules/ModuleLiquidity/Add/DetailsRow.vue')['default']
    ModuleLiquidityAddExchangeRate: typeof import('./modules/ModuleLiquidity/Add/ExchangeRate.vue')['default']
    ModuleLiquidityAddModal: typeof import('./modules/ModuleLiquidity/Add/Modal.vue')['default']
    ModuleLiquidityRemove: typeof import('./modules/ModuleLiquidity/Remove/index.vue')['default']
    ModuleLiquidityRemoveAmount: typeof import('./modules/ModuleLiquidity/Remove/Amount/index.vue')['default']
    ModuleLiquidityRemoveDetailed: typeof import('./modules/ModuleLiquidity/Remove/Detailed/index.vue')['default']
    ModuleLiquidityView: typeof import('./modules/ModuleLiquidity/View.vue')['default']
    ModuleLiquidityViewPairsList: typeof import('./modules/ModuleLiquidity/View/PairsList.vue')['default']
    ModuleLiquidityViewPairsListItem: typeof import('./modules/ModuleLiquidity/View/PairsListItem.vue')['default']
    ModuleSwapDetails: typeof import('./modules/ModuleSwap/Details.vue')['default']
    ModuleSwapExchangeRate: typeof import('./modules/ModuleSwap/ExchangeRate.vue')['default']
    NotificationsInit: typeof import('./components/NotificationsInit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagName: typeof import('./components/TagName.vue')['default']
    TokenInput: typeof import('./components/TokenInput.vue')['default']
    TokenSelect: typeof import('./components/TokenSelect/index.vue')['default']
    TokenSelectModal: typeof import('./components/TokenSelect/Modal.vue')['default']
    Tutorial: typeof import('./components/Tutorial.vue')['default']
  }
}

export {}
