/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftKip7PermitSol from "./draft-KIP7Permit.sol";
export type { draftKip7PermitSol };
export type { KIP7Votes } from "./KIP7Votes";
