/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ikipRecieverSol from "./IKIPReciever.sol";
export type { ikipRecieverSol };
import type * as draftIkip7PermitSol from "./draft-IKIP7Permit.sol";
export type { draftIkip7PermitSol };
export type { IAccessControl } from "./IAccessControl";
export type { IDexCallee } from "./IDexCallee";
export type { IDexFactory } from "./IDexFactory";
export type { IDexKIP7 } from "./IDexKIP7";
export type { IDexPair } from "./IDexPair";
export type { IDexRouter } from "./IDexRouter";
export type { IERC20 } from "./IERC20";
export type { IKIP13 } from "./IKIP13";
export type { IKIP7 } from "./IKIP7";
export type { IKIP7Metadata } from "./IKIP7Metadata";
export type { IKIP7Receiver } from "./IKIP7Receiver";
export type { IPlatformToken } from "./IPlatformToken";
export type { IVotes } from "./IVotes";
export type { IWKLAY } from "./IWKLAY";
